---
name: Build

on:
  push:
    branches-ignore:
      - "l10n_master"
      - "gh-pages"
  workflow_dispatch:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-22.04
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Set up dotnet
        uses: actions/setup-dotnet@9211491ffb35dd6a6657ca4f45d43dfe6e97c829
        with:
          dotnet-version: "6.0.x"

      - name: Print environment
        run: |
          dotnet --info
          nuget help | grep Version
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event: $GITHUB_EVENT"

      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Restore
        run: dotnet restore --locked-mode
        shell: pwsh

      - name: Remove SQL proj
        run: dotnet sln bitwarden-server.sln remove src/Sql/Sql.sqlproj

      - name: Build OSS solution
        run: dotnet build bitwarden-server.sln -p:Configuration=Debug -p:DefineConstants="OSS" --verbosity minimal
        shell: pwsh

      - name: Build solution
        run: dotnet build bitwarden-server.sln -p:Configuration=Debug --verbosity minimal
        shell: pwsh

      - name: Test OSS solution
        run: dotnet test ./test/Identity.IntegrationTest --no-build --verbosity d  -- xunit.maxParallelThreads=8
        shell: pwsh

      - name: Report test results
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226
        if: always()
        with:
          name: Test Results
          path: "**/*-test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
